name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリのチェックアウト
        uses: actions/checkout@v4

      - name: Python のセットアップ
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: 依存ライブラリのインストール
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-xdist matplotlib numpy pandas scikit-learn statsmodels

      - name: ユニットテストの実行
        run: pytest -n auto
      
      - name: Gist 更新スクリプトの実行
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: python update_gist.py
